const { Company, User } = require('../models'); // Import both Company and User models
const { default: logger } = require('../utils/logger');
const { UniqueConstraintError, ValidationError } = require('sequelize');
const { createCompanySchema } = require('../schemas/companySchemas');

exports.createCompany = async (req, res, next) => {
  try {
    const { name, address, phone, email } = req.body;
    const userId = req.user.id; // Get the ID of the authenticated user from the auth middleware

    // 1. Input Validation using Joi
    const { error } = createCompanySchema.validate(req.body);
    if (error) {
      logger.warn(`Validation error during company creation: ${error.details[0].message}`);
      return res.status(400).json({
        message: 'Company creation failed due to invalid input',
        error: error.details[0].message
      });
    }

    // 2. Create Company
    const company = await Company.create({ name, address, phone, email });

    // 3. Associate the created company with the user
    // This uses the Sequelize "add" method for many-to-many associations
    const user = await User.findByPk(userId);
    if (user) {
      await user.addCompany(company); // This method is generated by Sequelize's belongsToMany
      logger.info(`User ${user.email} (ID: ${userId}) associated with new company ${company.name}`);
    } else {
      logger.warn(`User with ID ${userId} not found during company association.`);
      // You might want to handle this more robustly,
      // though authMiddleware should ensure req.user.id exists for valid tokens.
    }

    // 4. Log Success
    logger.info(`New company created successfully: ${company.name} (ID: ${company.id})`);

    // 5. Send Success Response
    res.status(201).json({
      message: 'Company created successfully',
      company: {
        id: company.id,
        name: company.name,
        address: company.address,
        phone: company.phone,
        email: company.email,
      }
    });

  } catch (err) {
    // ... (your existing error handling code)
    if (err instanceof UniqueConstraintError) {
      let errorMessage = 'Company creation failed.';
      if (err.errors && err.errors.length > 0) {
        const uniqueField = err.errors[0].path;
        errorMessage = `The <span class="math-inline">\{uniqueField\} '</span>{req.body[uniqueField]}' is already in use.`;
      }
      logger.warn(`Company creation failed: ${errorMessage}`);
      return res.status(409).json({
        message: 'Company creation failed',
        error: errorMessage
      });
    } else if (err instanceof ValidationError) {
      logger.error(`Sequelize validation error during company creation: ${err.message}`);
      return res.status(400).json({
        message: 'Company creation failed due to invalid data',
        error: err.message
      });
    }
    logger.error(`An unexpected error occurred during company creation: ${err.message}`, { stack: err.stack });
    next(err);
  }
};